// Textos del módulo Calificaciones (BT 4.6, doc 05 §6, doc 13 F15), versión simplificada.

export const textosCalificaciones = {
  titulo: "Calificaciones",
  intro: "Calificación anual por funcionario: puntaje final según la escala del reglamento, lista resultante y anotaciones de mérito o demérito. La lista que otorga la asignación de mérito se define en Parámetros (regla Calificación).",
  procesos: "Procesos",
  nuevoProceso: "Nuevo proceso",
  dialogoProceso: { titulo: "Nuevo proceso de calificación", nombre: "Nombre", periodoDesde: "Período desde", periodoHasta: "Período hasta", enviar: "Crear", exito: "Proceso creado" },
  estados: { ABIERTO: "Abierto", CERRADO: "Cerrado" },
  cerrar: "Cerrar proceso",
  reabrir: "Reabrir",
  cerrado: "Proceso cerrado",
  reabierto: "Proceso reabierto",
  columnasProceso: { nombre: "Proceso", periodo: "Período", estado: "Estado", calificados: "Calificados" },
  ver: "Ver",
  sinProcesos: "Aún no hay procesos de calificación.",
  elegirProceso: "Elige un proceso para calificar.",
  filtros: { buscar: "Funcionario", pendientes: "Solo sin calificar", aplicar: "Filtrar", limpiar: "Limpiar" },
  columnas: { funcionario: "Funcionario", establecimiento: "Establecimiento", puntaje: "Puntaje final", lista: "Lista", notas: "Anotaciones", acciones: "Acciones" },
  sinCalificar: "Sin calificar",
  merito: "mérito",
  demerito: "demérito",
  calificar: "Calificar",
  editar: "Editar",
  dialogoCalificar: {
    titulo: (nombre: string) => `Calificar a ${nombre}`,
    descripcion: (min: number, max: number, lista: string) => `Escala de ${min} a ${max}. La lista se asigna según la regla vigente; la asignación de mérito corresponde a ${lista}.`,
    puntaje: "Puntaje final",
    observaciones: "Observaciones",
    enviar: "Guardar calificación",
    exito: "Calificación guardada",
  },
  anotar: "Anotar",
  dialogoNota: { titulo: "Anotación de mérito o demérito", tipo: "Tipo", tipos: [{ valor: "MERITO", etiqueta: "Mérito" }, { valor: "DEMERITO", etiqueta: "Demérito" }], descripcion: "Descripción", fecha: "Fecha", enviar: "Anotar", exito: "Anotación registrada" },
  vacio: "No hay funcionarios que coincidan con los filtros.",
  resumen: (calificados: number, total: number) => `${calificados} de ${total} funcionarios calificados`,
  ficha: { vacio: "Sin calificaciones registradas.", proceso: "Proceso", puntaje: "Puntaje final", lista: "Lista", notas: "Anotaciones", observaciones: "Observaciones" },
} as const;
