// Textos del módulo Calificaciones (BT 4.6, doc 05 §6, doc 13 F15).

export const textosCalificaciones = {
  titulo: "Calificaciones",
  intro: "Calificación anual por funcionario: notas por factor y subfactor según la ponderación del proceso, puntaje final calculado, lista según la regla vigente, acta adjunta y anotaciones de mérito o demérito. La lista que otorga la asignación de mérito se define en Parámetros (regla Calificación).",
  procesos: "Procesos",
  nuevoProceso: "Nuevo proceso",
  dialogoProceso: { titulo: "Nuevo proceso de calificación", nombre: "Nombre", periodoDesde: "Período desde", periodoHasta: "Período hasta", enviar: "Crear", exito: "Proceso creado" },
  estados: { ABIERTO: "Abierto", CERRADO: "Cerrado" },
  cerrar: "Cerrar proceso",
  reabrir: "Reabrir",
  cerrado: "Proceso cerrado",
  reabierto: "Proceso reabierto",
  columnasProceso: { nombre: "Proceso", periodo: "Período", estado: "Estado", calificados: "Calificados" },
  ver: "Ver",
  sinProcesos: "Aún no hay procesos de calificación.",
  elegirProceso: "Elige un proceso para calificar.",
  soloAbierto: "El proceso está cerrado: reábrelo para modificar la comisión, los factores o las calificaciones.",
  comision: {
    titulo: "Comisión evaluadora",
    vacio: "Sin integrantes registrados.",
    agregar: "Agregar integrante",
    quitar: "Quitar",
    quitado: "Integrante quitado",
    dialogo: {
      titulo: "Agregar integrante a la comisión",
      nombre: "Nombre",
      rol: "Rol en la comisión",
      rolAyuda: "Por ejemplo: Presidente/a, Integrante, Representante de la Asociación de Funcionarios.",
      enviar: "Agregar",
      exito: "Integrante agregado",
    },
  },
  factores: {
    titulo: "Factores y ponderación",
    vacio: "Sin factores: el puntaje final se registra directamente.",
    agregar: "Agregar factor",
    quitar: "Quitar",
    quitado: "Factor eliminado",
    copiar: (proceso: string) => `Copiar factores de ${proceso}`,
    copiados: (n: number) => `${n} factores copiados`,
    suma: (total: string) => `Los factores principales suman ${total} %.`,
    ponderacion: (p: string) => `${p} %`,
    dialogo: {
      titulo: "Agregar factor o subfactor",
      nombre: "Nombre",
      ponderacion: "Ponderación (%)",
      padre: "Subfactor de",
      padreAyuda: "Vacío: factor principal. Con un factor elegido: subfactor, se califica dentro de él.",
      enviar: "Agregar",
      exito: "Factor agregado",
    },
  },
  filtros: { buscar: "Funcionario", pendientes: "Solo sin calificar", aplicar: "Filtrar", limpiar: "Limpiar" },
  columnas: { funcionario: "Funcionario", establecimiento: "Establecimiento", puntaje: "Puntaje final", lista: "Lista", acta: "Acta", notas: "Anotaciones", acciones: "Acciones" },
  sinCalificar: "Sin calificar",
  merito: "mérito",
  demerito: "demérito",
  calificar: "Calificar",
  editar: "Editar",
  dialogoCalificar: {
    titulo: (nombre: string) => `Calificar a ${nombre}`,
    descripcion: (min: number, max: number, lista: string) => `Escala de ${min} a ${max}. La lista se asigna según la regla vigente; la asignación de mérito corresponde a ${lista}.`,
    notas: "Notas por factor",
    nota: "Nota",
    puntaje: "Puntaje final",
    calculado: "Puntaje final calculado",
    incompleto: "Completa todas las notas para calcular el puntaje.",
    lista: (lista: string | null) => (lista ? `Lista: ${lista}` : "Sin lista"),
    acta: "Acta o certificado (opcional)",
    actaAyuda: "PDF, JPG o PNG hasta 10 MB; queda en los documentos del funcionario.",
    actaActual: "Ya tiene acta adjunta; si subes otra, la reemplaza.",
    observaciones: "Observaciones",
    enviar: "Guardar calificación",
    guardando: "Guardando…",
    cancelar: "Cancelar",
    exito: "Calificación guardada",
  },
  acta: {
    ver: "Ver acta",
    sinActa: "Sin acta",
    adjuntar: "Adjuntar acta",
    dialogo: {
      titulo: (nombre: string) => `Adjuntar acta de ${nombre}`,
      descripcion: "Acta de la comisión o certificado de calificación, en PDF, JPG o PNG hasta 10 MB. Queda en los documentos del funcionario.",
      archivo: "Archivo",
      enviar: "Adjuntar",
      exito: "Acta adjuntada",
    },
  },
  anotar: "Anotar",
  dialogoNota: { titulo: "Anotación de mérito o demérito", tipo: "Tipo", tipos: [{ valor: "MERITO", etiqueta: "Mérito" }, { valor: "DEMERITO", etiqueta: "Demérito" }], descripcion: "Descripción", fecha: "Fecha", enviar: "Anotar", exito: "Anotación registrada" },
  vacio: "No hay funcionarios que coincidan con los filtros.",
  resumen: (calificados: number, total: number) => `${calificados} de ${total} funcionarios calificados`,
  ficha: { vacio: "Sin calificaciones registradas.", proceso: "Proceso", puntaje: "Puntaje final", lista: "Lista", porFactor: "Notas por factor", acta: "Acta", verActa: "Ver acta", sinActa: "—", notas: "Anotaciones", observaciones: "Observaciones" },
} as const;
