// Etiquetas en español para la bitácora (doc 05 §11, doc 12): acciones, entidades y campos frecuentes.

export const ACCIONES_AUDITORIA = ["CREAR", "APERTURA", "EDITAR", "ELIMINAR", "RECONOCER", "CALIFICAR", "IMPORTAR", "EXPORTAR", "LOGIN", "CAMBIO_REGLA"] as const;

export const ETIQUETAS_AUDITORIA = {
  accion: {
    CREAR: "Creación",
    APERTURA: "Apertura",
    EDITAR: "Edición",
    ELIMINAR: "Baja",
    RECONOCER: "Reconocimiento",
    CALIFICAR: "Calificación",
    IMPORTAR: "Importación",
    EXPORTAR: "Exportación",
    LOGIN: "Acceso",
    CAMBIO_REGLA: "Cambio de regla",
  } as Record<string, string>,
  entidad: {
    Funcionario: "Funcionario",
    Apertura: "Apertura",
    Experiencia: "Experiencia",
    Bienio: "Bienio",
    Capacitacion: "Capacitación",
    ExcedenteCapacitacion: "Excedente de capacitación",
    Estudio: "Estudio",
    NivelHistorico: "Nivel",
    ProcesoCalificacion: "Proceso de calificación",
    CalificacionFuncionario: "Calificación",
    Documento: "Documento",
    ReglaCarrera: "Regla de carrera",
    Alerta: "Alerta",
    Reporte: "Reporte",
    Auditoria: "Bitácora",
    Establecimiento: "Establecimiento",
    Institucion: "Institución",
    User: "Usuario",
    Respaldo: "Respaldo",
  } as Record<string, string>,
  campo: {
    rut: "RUT",
    nombres: "Nombres",
    apellidos: "Apellidos",
    email: "Correo",
    categoria: "Categoría",
    tipoContrato: "Tipo de contrato",
    fechaIngreso: "Fecha de ingreso",
    fechaNacimiento: "Fecha de nacimiento",
    establecimientoId: "Establecimiento (id)",
    cargo: "Cargo",
    jornadaHoras: "Jornada (horas)",
    estado: "Estado",
    fechaEgreso: "Fecha de egreso",
    motivoEgreso: "Motivo de egreso",
    nombre: "Nombre",
    institucion: "Institución",
    institucionDicta: "Institución que dicta",
    tipo: "Tipo",
    horas: "Horas",
    fechaInicio: "Fecha de inicio",
    fechaTermino: "Fecha de término",
    notaOEvaluacion: "Nota o evaluación",
    aprobado: "Aprobada",
    esOtraComuna: "Otra comuna",
    periodo: "Período",
    puntajeCalculado: "Puntaje calculado",
    puntajeAplicado: "Puntaje aplicado",
    numero: "Número",
    fechaCumplido: "Fecha cumplido",
    fechaReconocido: "Fecha reconocido",
    decretoNumero: "Número de decreto",
    decretoFecha: "Fecha del decreto",
    puntaje: "Puntaje",
    nivel: "Nivel",
    fechaDesde: "Desde",
    fechaHasta: "Hasta",
    puntajeAlCambio: "Puntaje al cambio",
    motivo: "Motivo",
    fechaObtencion: "Fecha de obtención",
    reconocidoEl: "Reconocido el",
    reconocidaEl: "Reconocida el",
    esPropia: "Propia",
    fecha: "Fecha",
    nivelDesde: "Nivel desde",
    puntajeTotal: "Puntaje total",
    puntajeExperiencia: "Puntaje de experiencia",
    puntajeCapacitacion: "Puntaje de capacitación",
    desglosado: "Desglosado",
    fechaUltimoBienio: "Fecha del último bienio",
    bieniosReconocidos: "Bienios reconocidos",
    excedentePendiente: "Excedente pendiente",
    fuente: "Fuente",
    vigenteDesde: "Vigente desde",
    vigenteHasta: "Vigente hasta",
    parametros: "Parámetros",
    mensaje: "Mensaje",
    fechaHito: "Fecha del hito",
    resolucionNota: "Nota de resolución",
    atendidaEl: "Atendida el",
    atendidaPorId: "Atendida por (id)",
    generadaEl: "Generada el",
    formato: "Formato",
    alcance: "Alcance",
    fechaCorte: "Situación al",
    filas: "Filas",
    filtros: "Filtros",
    nuevas: "Nuevas",
    actualizadas: "Actualizadas",
    resueltas: "Resueltas",
    activas: "Activas",
    documentoId: "Documento (id)",
    reglaId: "Regla (id)",
    funcionarioId: "Funcionario (id)",
    id: "Id",
    createdAt: "Creado el",
  } as Record<string, string>,
} as const;
