export const textosNuevo = {
  titulo: "Nuevo funcionario",
  volver: "Funcionarios",
  datos: "Datos del funcionario",
  apertura: "Saldo de apertura",
  conApertura: "Ingresa con puntaje y nivel reconocidos (saldo de apertura)",
  conAperturaAyuda: "Para funcionarios que ya tienen carrera: el grado y puntaje vigentes según la planilla del Departamento. Sin marcar, entra al nivel de ingreso sin puntaje.",
  campos: {
    rut: "RUT",
    nombres: "Nombres",
    apellidos: "Apellidos",
    fechaNacimiento: "Fecha de nacimiento",
    email: "Correo",
    categoria: "Categoría",
    tipoContrato: "Tipo de contrato",
    fechaIngreso: "Fecha de ingreso",
    establecimiento: "Establecimiento",
    cargo: "Cargo",
    jornada: "Jornada (horas)",
    aperturaFecha: "Saldos al",
    aperturaFechaAyuda: "Día al que corresponden los saldos, normalmente la víspera de la puesta en marcha.",
    aperturaNivel: "Grado (nivel) vigente",
    aperturaNivelDesde: "Rige desde",
    aperturaPuntajeTotal: "Puntaje total vigente",
    aperturaDesglosado: "El puntaje viene desglosado en experiencia y capacitación",
    aperturaPuntajeExperiencia: "Puntaje de experiencia",
    aperturaPuntajeCapacitacion: "Puntaje de capacitación",
    aperturaFechaUltimoBienio: "Fecha del último bienio reconocido",
    aperturaBieniosReconocidos: "N° de bienios reconocidos",
    aperturaExcedentePendiente: "Excedente de capacitación pendiente",
    aperturaFuente: "Fuente",
    aperturaFuenteAyuda: "Por ejemplo: Planilla del Departamento, octubre de 2026.",
  },
  guardar: "Crear funcionario",
  guardando: "Creando…",
  exito: "Funcionario creado",
  cancelar: "Cancelar",
} as const;
