// Textos del módulo Alertas (doc 05 §9, doc 12).

export const textosAlertas = {
  titulo: "Alertas",
  intro: "Avisos automáticos que el sistema genera a partir del cálculo de carrera: bienios próximos y sin reconocer, niveles alcanzados o próximos, cierres de período, calificaciones pendientes y documentos faltantes.",
  activas: (n: number) => (n === 1 ? "1 alerta activa" : `${n} alertas activas`),
  sincronizar: "Sincronizar ahora",
  sincronizando: "Sincronizando…",
  sincronizada: (nuevas: number, resueltas: number) => `Alertas sincronizadas: ${nuevas} nuevas, ${resueltas} resueltas`,
  exportar: "Exportar (Reportes)",
  filtros: {
    buscar: "Funcionario",
    tipo: "Tipo",
    establecimiento: "Establecimiento",
    estado: "Estado",
    desde: "Hito desde",
    hasta: "Hito hasta",
    todos: "Todos",
    todas: "Todas",
    aplicar: "Filtrar",
    limpiar: "Limpiar",
  },
  estados: { ACTIVA: "Activa", ATENDIDA: "Atendida", DESCARTADA: "Descartada" },
  columnas: { funcionario: "Funcionario", establecimiento: "Establecimiento", tipo: "Tipo", hito: "Fecha del hito", detalle: "Detalle", estado: "Estado", acciones: "Acciones" },
  vacio: "No hay alertas que coincidan con los filtros.",
  resolucion: (quien: string | null, cuando: string) => (quien ? `${quien}, ${cuando}` : cuando),
  atender: {
    boton: "Atender",
    titulo: "Atender alerta",
    descripcion: "Deja constancia de lo que se hizo. La alerta queda atendida y sale de la lista de activas.",
    nota: "Nota",
    enviar: "Atender",
    exito: "Alerta atendida",
  },
  descartar: {
    boton: "Descartar",
    titulo: "Descartar alerta",
    descripcion: "Para avisos que no corresponden. Indica el motivo; no se volverá a generar mientras el hecho no cambie.",
    nota: "Motivo",
    enviar: "Descartar",
    exito: "Alerta descartada",
  },
  paginacion: { anterior: "Anterior", siguiente: "Siguiente", mostrando: (desde: number, hasta: number, total: number) => `${desde} a ${hasta} de ${total}` },
} as const;
