// Textos de los diálogos de acción de la ficha (doc 12: infinitivo en botones, mismo verbo en la confirmación).

export const textosAcciones = {
  capacitacion: {
    boton: "Registrar capacitación",
    titulo: "Registrar capacitación",
    descripcion: (nombre: string) => `El puntaje se calcula con la tabla vigente a la fecha de término y entra al período que corresponda. Funcionario: ${nombre}.`,
    nombre: "Nombre de la actividad",
    institucion: "Institución que la dicta",
    tipo: "Tipo",
    tipos: [
      { valor: "CURSO", etiqueta: "Curso" },
      { valor: "DIPLOMADO", etiqueta: "Diplomado" },
      { valor: "SEMINARIO", etiqueta: "Seminario" },
      { valor: "PASANTIA", etiqueta: "Pasantía" },
      { valor: "OTRO", etiqueta: "Otro" },
    ],
    horas: "Horas",
    nota: "Nota o evaluación",
    notaAyuda: "Opcional, de 1 a 7.",
    inicio: "Fecha de inicio",
    termino: "Fecha de término",
    periodo: "Período",
    periodoAyuda: "Si se deja vacío, el año de la fecha de término.",
    aprobada: "Aprobada",
    otraComuna: "Realizada en otra comuna",
    enviar: "Registrar",
    exito: "Capacitación registrada",
  },
  bienio: {
    boton: "Reconocer",
    titulo: (numero: number) => `Reconocer bienio ${numero}`,
    descripcion: (fecha: string, puntos: string) => `Cumplido el ${fecha}, ${puntos} puntos según la regla vigente a esa fecha. Registra el decreto que lo reconoce.`,
    decretoNumero: "Número de decreto",
    decretoFecha: "Fecha del decreto",
    enviar: "Reconocer",
    exito: "Bienio reconocido",
  },
  nivel: {
    boton: "Registrar cambio de nivel",
    titulo: "Registrar cambio de nivel",
    descripcion: (vigente: number, calculado: number) => `Nivel vigente ${vigente}; nivel calculado con el puntaje acumulado: ${calculado}. El cambio rige desde la fecha indicada.`,
    nivel: "Nivel nuevo",
    nivelAyuda: (calculado: number) => `Propuesto según el puntaje: ${calculado}.`,
    desde: "Rige desde",
    decretoNumero: "Número de decreto",
    decretoFecha: "Fecha del decreto",
    motivo: "Motivo",
    motivos: [
      { valor: "ASCENSO", etiqueta: "Ascenso" },
      { valor: "HOMOLOGACION", etiqueta: "Homologación" },
      { valor: "AJUSTE", etiqueta: "Ajuste" },
    ],
    enviar: "Registrar",
    exito: "Nivel actualizado",
  },
  estudio: {
    boton: "Registrar estudio",
    titulo: "Registrar estudio",
    tipo: "Tipo",
    tipos: [
      { valor: "TITULO", etiqueta: "Título" },
      { valor: "DIPLOMADO", etiqueta: "Diplomado" },
      { valor: "POSTITULO", etiqueta: "Postítulo" },
      { valor: "MAGISTER", etiqueta: "Magíster" },
      { valor: "DOCTORADO", etiqueta: "Doctorado" },
    ],
    nombre: "Nombre",
    institucion: "Institución",
    obtencion: "Fecha de obtención",
    reconocido: "Fecha de reconocimiento",
    reconocidoAyuda: "Sin reconocimiento no puntúa.",
    enviar: "Registrar",
    exito: "Estudio registrado",
  },
  experiencia: {
    boton: "Registrar experiencia",
    titulo: "Registrar período de experiencia",
    descripcion: "Un período en esta institución o experiencia reconocida de otro servicio o centro de salud.",
    institucion: "Institución",
    desde: "Desde",
    hasta: "Hasta",
    hastaAyuda: "Vacío si sigue vigente.",
    jornada: "Jornada (horas)",
    reconocida: "Reconocida el",
    reconocidaAyuda: "Obligatoria para experiencia externa: fecha del acto que la reconoce.",
    propia: "Es un período en esta institución",
    enviar: "Registrar",
    exito: "Experiencia registrada",
  },
  datos: {
    boton: "Editar datos",
    titulo: "Editar datos del funcionario",
    rut: "RUT",
    email: "Correo",
    nombres: "Nombres",
    apellidos: "Apellidos",
    fechaNacimiento: "Fecha de nacimiento",
    categoria: "Categoría",
    tipoContrato: "Tipo de contrato",
    fechaIngreso: "Fecha de ingreso",
    establecimiento: "Establecimiento",
    cargo: "Cargo",
    jornada: "Jornada (horas)",
    enviar: "Guardar",
    exito: "Datos guardados",
  },
  baja: {
    boton: "Dar de baja",
    titulo: "Dar de baja",
    descripcion: "El funcionario queda inactivo con fecha y motivo de egreso; su historial se conserva. No se borra nada.",
    fechaEgreso: "Fecha de egreso",
    motivo: "Motivo",
    enviar: "Dar de baja",
    exito: "Funcionario dado de baja",
  },
} as const;
