// Textos del área administrativa (doc 12). Los nombres de menú son los de las bases, en su orden.

export const textosShell = {
  producto: "Carrera APS",
  abrirMenu: "Abrir menú",
  notaDemo: "Datos de demostración; dotación ficticia",
  cerrarSesion: "Cerrar sesión",
  roles: {
    ADMIN: "Administración",
    SUPERVISION: "Supervisión",
    FUNCIONARIO: "Funcionario",
  },
  menu: {
    principal: [
      { href: "/", etiqueta: "Inicio", icono: "inicio" },
      { href: "/funcionarios", etiqueta: "Funcionarios", icono: "funcionarios" },
      { href: "/carrera", etiqueta: "Carrera", icono: "carrera" },
      { href: "/capacitaciones", etiqueta: "Capacitaciones", icono: "capacitaciones" },
      { href: "/calificaciones", etiqueta: "Calificaciones", icono: "calificaciones" },
      { href: "/reportes", etiqueta: "Reportes", icono: "reportes" },
      { href: "/alertas", etiqueta: "Alertas", icono: "alertas" },
      { href: "/documentos", etiqueta: "Documentos", icono: "documentos" },
      { href: "/parametros", etiqueta: "Parámetros", icono: "parametros" },
      { href: "/auditoria", etiqueta: "Auditoría", icono: "auditoria" },
      { href: "/respaldos", etiqueta: "Respaldos", icono: "respaldos" },
    ],
    administracion: [
      { href: "/importar", etiqueta: "Importar", icono: "importar" },
      { href: "/exportacion-integral", etiqueta: "Exportación integral", icono: "exportacion" },
      { href: "/usuarios", etiqueta: "Usuarios", icono: "usuarios" },
    ],
  },
  /** Rutas que puede ver SUPERVISION (lee, no edita): doc 05 */
  rutasSupervision: ["/", "/funcionarios", "/capacitaciones", "/reportes", "/alertas", "/documentos", "/auditoria"],
} as const;

export const textosInicio = {
  titulo: "Inicio",
  situacion: (fecha: string) => `Situación al ${fecha}, calculada en vivo`,
  dotacion: "Dotación activa",
  inactivos: "Inactivos (con fecha de egreso)",
  antiguedadPromedio: "Antigüedad promedio",
  anios: (n: string) => `${n} años`,
  puntajePromedio: "Puntaje promedio",
  puntos: (n: number) => `${n} puntos`,
  porEstablecimiento: "Por establecimiento",
  porCategoria: "Por categoría",
  porNivel: "Dotación por nivel",
  nivel: (n: number) => `Nivel ${n}`,
  bieniosProximos: "Bienios próximos a cumplirse",
  en30: "30 días",
  en60: "60 días",
  en90: "90 días",
  sinReconocer: "Cumplidos sin decreto de reconocimiento",
  proximosBienios: "Próximos bienios (90 días)",
  bienioN: (n: number) => `Bienio ${n}`,
  enDias: (d: number) => (d === 0 ? "hoy" : d === 1 ? "mañana" : `en ${d} días`),
  sinProximos: "Ningún bienio se cumple en los próximos 90 días.",
  cumplenAscenso: "Cumplen requisitos de ascenso",
  cercaDeNivel: "A 10 puntos o menos del siguiente nivel",
  masCerca: "Más cerca del siguiente nivel",
  faltanPara: (puntos: string, nivel: number) => `faltan ${puntos} para el nivel ${nivel}`,
  sinCerca: "Nadie está a 10 puntos o menos del siguiente nivel.",
  alertasActivas: "Alertas activas",
  calificacion: "Calificación",
  calificados: (n: number, total: number) => `${n} de ${total}`,
  pendientes: (n: number) => (n === 1 ? "1 funcionario sin calificar" : `${n} funcionarios sin calificar`),
  listas: "Funcionarios por lista",
  verCalificaciones: "Ir a calificar",
  sinProceso: "No hay un proceso de calificación abierto.",
  capacitacion: (anio: number) => `Capacitación ${anio}`,
  actividades: "actividades registradas en el período",
  conActividad: "Funcionarios con actividad",
  puntosAplicados: "Puntos aplicados al período",
  conTope: "Con el tope anual alcanzado",
  verCapacitaciones: "Ver capacitaciones",
  actividadReciente: "Actividad reciente",
  sinActividad: "Sin movimientos registrados.",
  verAuditoria: "Ver auditoría completa",
  sistema: "Sistema",
  ultimoRespaldo: "Último respaldo",
  ultimoVerificado: "Último verificado por restauración",
  sinRespaldo: "Sin registro",
  documentos: "Documentos adjuntos",
  documentosDe: (total: number, funcionarios: number) => `${total} · ${funcionarios} funcionarios con documentos`,
  verRespaldos: "Ver respaldos",
  verDocumentos: "Ver documentos",
  verAlertas: "Ver alertas",
  verFuncionarios: "Ver funcionarios",
  verReportes: "Ver reportes",
  funcionarios: "funcionarios",
  sinAlertas: "Sin alertas activas",
} as const;
