// Textos del módulo Parámetros (doc 05 §10, doc 13 F12, doc 12).

export const textosParametros = {
  titulo: "Parámetros",
  intro: "El reglamento comunal como parámetros con vigencia (BT 5): cada regla tiene versiones; una versión nueva rige desde su fecha y la anterior se cierra el día anterior. Los cálculos a una fecha usan la regla vigente entonces.",
  reglas: {
    titulo: "Reglas de carrera",
    vigente: "Vigente hoy",
    sinVigente: "Sin regla vigente: el motor usa el valor por defecto del doc 04 o la omite.",
    desde: "desde",
    hasta: "hasta",
    categoria: (c: string | null) => (c ? `Categoría ${c}` : "Todas las categorías"),
    fuente: "Fuente",
    historial: "Historial de versiones",
    nuevaVersion: "Nueva versión",
    dialogo: {
      titulo: (regla: string) => `Nueva versión: ${regla}`,
      descripcion: "Los cálculos desde esa fecha usarán la nueva regla; los reportes a fechas anteriores no cambian. La versión vigente se cierra el día anterior.",
      categoria: "Categoría",
      todas: "Todas las categorías",
      vigenteDesde: "Vigente desde",
      fuente: "Fuente",
      fuenteAyuda: "Artículo del reglamento comunal o número de decreto.",
      parametros: "Parámetros de la regla",
      parametrosAyuda: "Vienen cargados con la versión vigente: cambia solo lo que fija el reglamento. Se validan antes de guardar.",
      tablaVacia: "Sin filas todavía.",
      quitarFila: "Quitar",
      agregarTramo: "Agregar tramo",
      agregarNivel: "Agregar nivel",
      agregarLista: "Agregar lista",
      errores: {
        numero: "Escribe un número.",
        entero: "Escribe un número entero.",
        tramos: "Agrega al menos un tramo de horas.",
        umbrales: "Agrega al menos un nivel con su puntaje mínimo.",
        listas: "Agrega al menos una lista.",
        nombreLista: "Escribe el nombre de la lista.",
        listaConMerito: "Elige una de las listas de la tabla.",
        esquema: "La regla no tiene la forma esperada:",
      },
      cancelar: "Cancelar",
      guardando: "Guardando…",
      enviar: "Guardar versión",
      exito: "Nueva versión de la regla guardada",
    },
  },
  establecimientos: {
    titulo: "Establecimientos",
    columnas: { nombre: "Nombre", tipo: "Tipo", funcionarios: "Funcionarios", estado: "Estado" },
    activo: "Activo",
    inactivo: "Inactivo",
    nuevo: "Nuevo establecimiento",
    editar: "Editar",
    dialogoNuevo: { titulo: "Nuevo establecimiento", nombre: "Nombre", tipo: "Tipo", enviar: "Crear", exito: "Establecimiento creado" },
    dialogoEditar: { titulo: "Editar establecimiento", nombre: "Nombre", tipo: "Tipo", activo: "Activo (aparece en filtros y altas)", enviar: "Guardar", exito: "Establecimiento guardado" },
  },
  institucion: {
    titulo: "Institución",
    nombre: "Nombre",
    rut: "RUT",
    comuna: "Comuna",
    editar: "Editar",
    dialogo: { titulo: "Editar institución", nombre: "Nombre", comuna: "Comuna", enviar: "Guardar", exito: "Institución guardada" },
  },
  alertas: "Los días de aviso de las alertas se fijan en la regla \"Alertas\".",
} as const;
