// Textos del módulo Usuarios y accesos (doc 05 §16, doc 07).

export const textosUsuarios = {
  titulo: "Usuarios",
  intro: "Cuentas por rol: Administración (edita todo), Supervisión (solo lectura) y Funcionario (su portal). Las cuentas nuevas y las contraseñas restablecidas obligan a cambiar la contraseña al entrar. Los intentos de acceso quedan en el registro de accesos.",
  accesos: "Registro de accesos",
  nuevo: "Nuevo usuario",
  columnas: { nombre: "Nombre", correo: "Correo", rol: "Rol", funcionario: "Funcionario vinculado", estado: "Estado", ultimoAcceso: "Último acceso", acciones: "Acciones" },
  roles: { ADMIN: "Administración", SUPERVISION: "Supervisión", FUNCIONARIO: "Funcionario" } as Record<string, string>,
  activo: "Activa",
  desactivado: "Desactivada",
  pendienteCambio: "Debe cambiar la contraseña",
  nunca: "Nunca",
  editar: "Editar",
  restablecer: "Restablecer contraseña",
  desactivar: "Desactivar",
  reactivar: "Reactivar",
  dialogoNuevo: {
    titulo: "Nuevo usuario",
    descripcion: "Se genera una contraseña temporal que verás una sola vez; entrégala por un canal seguro. La persona deberá cambiarla en su primer ingreso.",
    nombre: "Nombre",
    correo: "Correo",
    rol: "Rol",
    funcionario: "Funcionario (portal)",
    sinFuncionario: "Sin vincular",
    enviar: "Crear cuenta",
    creando: "Creando…",
    cancelar: "Cancelar",
  },
  creado: {
    titulo: "Cuenta creada",
    texto: (correo: string) => `Contraseña temporal para ${correo}. No se volverá a mostrar.`,
    cerrar: "Entendido",
  },
  dialogoEditar: { titulo: "Editar cuenta", nombre: "Nombre", rol: "Rol", funcionario: "Funcionario (portal)", sinFuncionario: "Sin vincular", enviar: "Guardar", exito: "Cuenta guardada" },
  restablecida: { titulo: "Contraseña restablecida", texto: (correo: string) => `Nueva contraseña temporal para ${correo}; sus sesiones se cerraron y deberá cambiarla al entrar.`, cerrar: "Entendido" },
  estadoCambiado: { desactivada: "Cuenta desactivada", reactivada: "Cuenta reactivada" },
  vacio: "Sin cuentas.",
} as const;
