// Textos del módulo Funcionarios (doc 05 módulo 2, doc 12 glosario).

export const textosFuncionarios = {
  titulo: "Funcionarios",
  nuevo: "Nuevo funcionario",
  buscar: "Buscar por RUT o nombre",
  filtros: {
    establecimiento: "Establecimiento",
    categoria: "Categoría",
    tipoContrato: "Tipo de contrato",
    estado: "Estado",
    todos: "Todos",
    aplicar: "Filtrar",
    limpiar: "Limpiar",
  },
  columnas: {
    rut: "RUT",
    nombre: "Nombre",
    categoria: "Categoría",
    nivel: "Nivel",
    establecimiento: "Establecimiento",
    bienios: "Bienios",
    puntaje: "Puntaje",
    proximaAlerta: "Próxima alerta",
  },
  vacio: {
    titulo: "No hay funcionarios que coincidan con la búsqueda.",
    accion: "Limpiar filtros",
  },
  total: (n: number) => (n === 1 ? "1 funcionario" : `${n} funcionarios`),
  ficha: {
    volver: "Funcionarios",
    estado: { ACTIVO: "Activo", INACTIVO: "Inactivo" },
    contrato: { TITULAR: "Titular", PLAZO_FIJO: "Plazo fijo", REEMPLAZO: "Reemplazo" },
    pestanas: {
      datos: "Datos",
      experiencia: "Experiencia y bienios",
      capacitaciones: "Capacitaciones",
      estudios: "Estudios",
      nivel: "Nivel y proyección",
      calificaciones: "Calificaciones",
      documentos: "Documentos",
      historial: "Historial",
      alertas: "Alertas",
    },
    riel: {
      nivelIngreso: "Nivel de ingreso",
      nivelMaximo: "Nivel máximo",
      actual: "actual",
      nivelActual: "Nivel actual",
      siguiente: "siguiente",
      faltan: (puntos: string) => `faltan ${puntos}`,
      estimado: (mesAnio: string) => `estimado ${mesAnio}`,
      sinProyeccion: "sin proyección",
      nivelMaximoAlcanzado: "nivel máximo",
      sinInformacion: "Sin información anterior a la puesta en marcha",
    },
    datos: {
      rut: "RUT",
      nombres: "Nombres",
      apellidos: "Apellidos",
      fechaNacimiento: "Fecha de nacimiento",
      email: "Correo",
      categoria: "Categoría",
      tipoContrato: "Tipo de contrato",
      fechaIngreso: "Fecha de ingreso",
      establecimiento: "Establecimiento",
      cargo: "Cargo",
      jornada: "Jornada",
      horas: "horas",
      estado: "Estado",
      fechaEgreso: "Fecha de egreso",
      motivoEgreso: "Motivo de egreso",
      editar: "Editar datos",
      darDeBaja: "Dar de baja",
      apertura: "Saldo de apertura",
      aperturaFecha: "Saldos al",
      aperturaTotal: "Puntaje total",
      aperturaDesglose: "Experiencia / capacitación",
      aperturaSinDesglose: "sin desglose",
      aperturaUltimoBienio: "Último bienio reconocido",
      aperturaFuente: "Fuente",
    },
    experiencia: {
      periodos: "Períodos de experiencia",
      institucion: "Institución",
      desde: "Desde",
      hasta: "Hasta",
      vigente: "vigente",
      propia: "Propia",
      reconocida: "Reconocida",
      reconocidaEl: "Reconocida el",
      registrar: "Registrar experiencia",
      bienios: "Bienios",
      numero: "N°",
      fechaCumplido: "Fecha cumplido",
      fechaReconocido: "Fecha reconocido",
      decreto: "Decreto",
      puntos: "Puntos",
      estado: "Estado",
      cumplidoSinReconocer: "Cumplido, sin reconocer",
      reconocido: "Reconocido",
      enSaldo: "En saldo de apertura",
      reconocer: "Reconocer",
      proximoBienio: "Próximo bienio",
      sinProximo: "Sin período de experiencia vigente",
      puntajeExperiencia: "Puntaje de experiencia",
      diasServicio: "Días de servicio",
    },
    capacitaciones: {
      registrar: "Registrar capacitación",
      actividad: "Actividad",
      horas: "Horas",
      termino: "Término",
      aprobada: "Aprobada",
      si: "Sí",
      no: "No",
      calculado: "Calculado",
      aplicado: "Aplicado",
      periodo: "Período",
      arrastre: "Arrastre",
      tope: "Tope",
      excedente: "Excedente",
      caducado: "Caducado",
      porPeriodo: "Resumen por período",
      total: "Puntaje de capacitación",
      saldoApertura: "En saldo de apertura",
      vacio: "Aún no hay capacitaciones registradas.",
    },
    estudios: {
      registrar: "Registrar estudio",
      tipo: "Tipo",
      nombre: "Nombre",
      institucion: "Institución",
      obtencion: "Obtención",
      reconocido: "Reconocido",
      puntos: "Puntos",
      beneficio: "Beneficio informativo",
      enSaldo: "En saldo de apertura",
      sinReconocer: "Sin reconocer",
      total: "Puntaje de estudios",
      vacio: "Aún no hay estudios registrados.",
      tipos: { TITULO: "Título", DIPLOMADO: "Diplomado", POSTITULO: "Postítulo", MAGISTER: "Magíster", DOCTORADO: "Doctorado" },
    },
    nivel: {
      vigente: "Nivel vigente",
      desde: "desde",
      calculado: "Nivel calculado",
      cumple: (nivel: number) => `Cumple requisitos para el nivel ${nivel}`,
      noCumple: "No cumple requisitos de ascenso todavía",
      registrarCambio: "Registrar cambio de nivel",
      desglose: "Puntaje acumulado",
      experiencia: "Experiencia",
      capacitacion: "Capacitación",
      estudios: "Estudios",
      otrosApertura: "Otros conceptos del saldo de apertura",
      saldoSinDesglose: "Saldo de apertura (sin desglose)",
      total: "Total",
      proyeccion: "Proyección",
      siguiente: "Nivel siguiente",
      umbral: "Puntaje requerido",
      faltan: "Puntaje faltante",
      fechaEstimada: "Fecha estimada",
      supuestos: "Supuestos",
      noAlcanzable: "No se alcanza con los supuestos actuales",
      historial: "Historial de niveles",
      motivo: "Motivo",
      motivos: { APERTURA: "Apertura", INGRESO: "Ingreso", ASCENSO: "Ascenso", HOMOLOGACION: "Homologación", AJUSTE: "Ajuste" },
      comoSeCalcula: "¿Cómo se calcula?",
    },
    alertas: { vacio: "Sin alertas activas para este funcionario.", tipo: "Tipo", hito: "Fecha del hito", mensaje: "Detalle" },
    historial: {
      vacio: "Sin cambios registrados.",
      fecha: "Fecha",
      usuario: "Usuario",
      accion: "Acción",
      entidad: "Entidad",
      detalle: "Detalle",
      verCambios: "Ver cambios",
      sinCambios: "Sin campos registrados",
      cambios: { titulo: "Cambios registrados", campo: "Campo", antes: "Valor anterior", despues: "Valor nuevo", cerrar: "Cerrar" },
    },
    proximamente: "Este módulo se habilita en la siguiente fase.",
    columnasNivel: { nivel: "Nivel", desde: "Desde", hasta: "Hasta", puntaje: "Puntaje al cambio" },
    nombresAlerta: {
      BIENIO_PROXIMO: "Bienio próximo",
      BIENIO_PENDIENTE_RECONOCER: "Bienio sin reconocer",
      NIVEL_ALCANZADO: "Nivel alcanzado",
      NIVEL_PROXIMO: "Nivel próximo",
      CAPACITACION_POR_VENCER_PERIODO: "Cierre de período",
      CALIFICACION_PENDIENTE: "Calificación pendiente",
      DOCUMENTO_FALTANTE: "Documento faltante",
    },
  },
} as const;
